Localtion:
  # 经度，纬度，海拔
  操场: [1, 2, 3]
  一号教学楼: [1, 2, 3]

Action:
  - 早操签到:
      location: 操场
      cron: "0 0 7 * * *"
  - 上课签到:
      location: 一号教学楼
      cron: "0 0 7 * * *"
  - 晚自习签到:
      location: 一号教学楼
      cron: "0 0 7 * * *"

Users:
  - name: 张三
    cookie: "123456"
    classID: "123456"
    events:
      - 早操签到
      - 上课签到
  - name: 李四
    cookie: "123456"
    classID: "123456"
    events:
      - 上课签到
      - 晚自习签到
