Localtion:
  # 纬度，经度，海拔
  操场: [1, 2, 3]
  一号教学楼: [1, 2, 3]

Action:
  早操签到:
    localtion: 操场
    cron: "* 7 * * *"
  上课签到:
    localtion: 一号教学楼
    cron: "* 8-17 * * *"
  晚自习签到:
    localtion: 一号教学楼
    cron: "* 19-20 * * *"

Users:
  - name: 张三
    cookie: "123456"
    classID: "123456"
    events:
      - 早操签到
      - 上课签到
  - name: 李四
    cookie: "123456"
    classID: "123456"
    events:
      - 上课签到
      - 晚自习签到

SearchTime: 60
